[project]
name = "fasturl"
version = "0.1.0"
description = "A Python project based on python-blueprint"
readme = "README.md"
requires-python = ">=3.10,<3.15"
dependencies = [
  "aiosqlite>=0.21",
  "asyncpg>=0.30.0",
  "fastapi>=0.115,<0.116",
  "httpx>=0.28",
  "loguru>=0.7",
  "pydantic>=2.3,<3",
  "pydantic-settings>=2.2.0",
  "pytest-asyncio>=0.25",
  "pyyaml>=6.0",
  "sqlalchemy[asyncio]>=2.0",
  "uvicorn[standard]>=0.34",
]

[dependency-groups]
dev = [
  "bandit>=1.8.6",
  "coverage>=7.11.0",
  "detect-secrets>=1.5.0",
  "mypy>=1.18.2",
  "poethepoet>=0.37.0",
  "pre-commit>=3.8.0",
  "pytest>=8.4.2",
  "pytest-asyncio>=0.25",
  "pytest-cov>=7.1.0",
  "radon>=6.0.1",
  "ruff>=0.8.0",
]

[tool.ruff]
exclude = [".venv", "__pycache__", "build", "dist", "*.egg-info"]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
ignore = []
select = ["E", "W", "F", "I", "N", "UP", "B", "C4", "SIM"]

[tool.ruff.lint.isort]
lines-between-types = 0
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.ruff.format]
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false

[tool.pytest.ini_options]
pythonpath = ["src"]
asyncio_mode = "auto"
testpaths = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning:fastapi.*",
]

[tool.poe.tasks]
test-unit        = "pytest tests/unit -v"
test-integration = "pytest tests/integration -v"
test             = "pytest tests/ -v"
test-cov         = "pytest tests/ --cov=src --cov-report=term-missing"
